title: 'PlhamJ documentation'

include: ['tutorial', 'class']

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

highlighter: null

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      math: true
theme: jekyll-theme-cayman